/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "main-background-t1": "#3a4764",
        "main-background-t2": "#e6e6e6",
        "main-background-t3": "#160628",
        "toggle-background-t1": "#232c43",
        "toggle-background-t2": "#d1cccc",
        "toggle-background-t3": "#1d0934",
        "screen-background-t1": "#182034",
        "screen-background-t2": "#ededed",
        "screen-background-t3": "#1d0934",
        "key-default-background-t1": "#eae3dc",
        "key-default-background-t2": "#e5e4e1",
        "key-default-background-t3": "#341c4f",
        "key-default-shadow-t1": "#b4a597",
        "key-default-shadow-t2": "#a69d91",
        "key-default-shadow-t3": "#871c9c",
        "key-command-background-t1": "#637097",
        "key-command-background-t2": "#377f86",
        "key-command-background-t3": "#58077d",
        "key-command-shadow-t1": "#404e72",
        "key-command-shadow-t2": "#1b5f65",
        "key-command-shadow-t3": "#bc15f4",
        "key-equal-background-t1": "#d03f2f",
        "key-equal-background-t2": "#ca5502",
        "key-equal-background-t3": "#00e0d1",
        "key-equal-shadow-t1": "#93261a",
        "key-equal-shadow-t2": "#893901",
        "key-equal-shadow-t3": "#6cf9f2",
        "text-key-default-t1": "#444b5a",
        "text-key-command-t1": "#ffffff",
        "text-key-equal-t1": "#ffffff",
        "text-key-default-t2": "#35352c",
        "text-key-command-t2": "#ffffff",
        "text-key-equal-t2": "#ffffff",
        "text-key-default-t3": "#ffe53d",
        "text-key-command-t3": "#ffffff",
        "text-key-equal-t3": "#1b2428",
        "text-default-t1": "#ffffff",
        "text-default-t2": "#35352c",
        "text-default-t3": "#ffe53d",
      },
    },
  },
  plugins: [],
};
